export default {
  SEARCH_TEXT_CHANGED: 'SEARCH_TEXT_CHANGED',
  SEARCH_CLICK: 'SEARCH_CLICK',
  TOGGEL_LOADING: 'DASHBOARD_TOGGEL_LOADING',
  SET_RECIPES_LIST: 'SET_RECIPES_LIST',
  SELECT_RECIPE: 'SELECT_RECIPE'
};
