const LOGIN_SUBMIT = "LOGIN";
const LOGIN_EMAIL_TEXT_CHANGED = "LOGIN_EMAIL_TEXT_CHANGED";
const LOGIN_PWD_TEXT_CHANGED = "LOGIN_PWD_TEXT_CHANGED";

export default {
  LOGIN_SUBMIT,
  LOGIN_EMAIL_TEXT_CHANGED,
  LOGIN_PWD_TEXT_CHANGED
};
