const BOOKMARK_LIST = 'BOOKMARK_LIST';
const RECIPE_LIST = 'RECIPE_LIST';
const MEALPLAN_LIST = 'MEALPLAN_LIST';
const TOGGLE_DIALOG = 'TOGGLE_DIALOG';
const REMOVE_RECIPE = 'REMOVE_RECIPE';

export default {
  TOGGEL_LOADING: 'RECIPES_TOGGEL_LOADING',
  SELECT_RECIPE: 'SELECT_RECIPE',
  SHOW_ERROR: 'SHOW_ERROR',

  BOOKMARK_LIST,
  RECIPE_LIST,
  MEALPLAN_LIST,
  TOGGLE_DIALOG,
  REMOVE_RECIPE,
};
