const SIGNUP_SUBMIT = "SIGNUP";
const LOGIN_SUBMIT = "LOGIN";
const LOGIN_EMAIL_TEXT_CHANGED = "LOGIN_EMAIL_TEXT_CHANGED";
const LOGIN_PWD_TEXT_CHANGED = "LOGIN_PWD_TEXT_CHANGED";
const LOGIN_PWD_CONFIRM = "LOGIN_PWD_CONFIRM";
const PROFILE_HANDLE_CHANGE = "PROFILE_HANDLE_CHANGE";
const PROFILE_SAVE_CHANGE = "PROFILE_SAVE_CHANGE";
const USER_DEFAULT = "USER_DEFAULT";
const PROFILE_DEFAULT = "PROFILE_DEFAULT";

export default {
  LOGIN_SUBMIT,
  LOGIN_EMAIL_TEXT_CHANGED,
  LOGIN_PWD_TEXT_CHANGED,
  LOGIN_PWD_CONFIRM,
  SIGNUP_SUBMIT,
  PROFILE_HANDLE_CHANGE,
  PROFILE_SAVE_CHANGE,
  USER_DEFAULT,
  PROFILE_DEFAULT
};
