export default {
  LOGIN: 'LOGIN',
  LOGIN_EMAIL_TEXT_CHANGED: 'LOGIN_EMAIL_TEXT_CHANGED',
  LOGIN_PWD_TEXT_CHANGED: 'LOGIN_PWD_TEXT_CHANGED',
  ADD_MEAL_PLANNER: 'ADD_MEAL_PLANNER',
  EDIT_MEAL_PLANNER: 'EDIT_MEAL_PLANNER',
};
