export default {
  LOGIN: 'LOGIN',
  LOGIN_EMAIL_TEXT_CHANGED: 'LOGIN_EMAIL_TEXT_CHANGED',
  LOGIN_PWD_TEXT_CHANGED: 'LOGIN_PWD_TEXT_CHANGED',
  SEARCH_TEXT_CHANGED: 'SEARCH_TEXT_CHANGED',
  SEARCH_CLICK: 'SEARCH_CLICK'
};
